# hatch
# Ref: https://hatch.pypa.io/latest/config/metadata/
# ------------------------------------------------------------------------------

[project]
name = "dummy"
description = "dummy"
readme = "README.md"
license = {text = "MIT"}
authors = [
  { name = "Heinz-Alexander Fütterer" },
]
requires-python = ">=3.10"
dynamic = [
  "version",
]

[build-system]
build-backend = "hatchling.build"
requires = [
  "hatchling",
]

[tool.hatch.build.targets.sdist]
include = [
  "src",
  "CHANGELOG.md",
]

[tool.hatch.build.targets.wheel]
packages = ["src/dummy"]

[tool.hatch.version]
path = "src/dummy/__about__.py"

[tool.hatch.envs.release]
dependencies = ["python-semantic-release"]

[tool.hatch.envs.release.scripts]
next-version = "semantic-release version --print"
update-citation = """
  sed -i "s/^version: .*/version: $(semantic-release version --print)/" CITATION.cff
  sed -i "s/^date-released: .*/date-released: $(date "+%Y-%m-%d")/" CITATION.cff
  cat CITATION.cff
"""

# python-semantic-release
# Ref: https://python-semantic-release.readthedocs.io/en/latest/configuration.html#settings
# ------------------------------------------------------------------------------

[tool.semantic_release]
commit_message = "chore: release {version}\n\nAutomatically generated by python-semantic-release [skip ci]"
logging_use_named_masks = true
major_on_zero = false
tag_format = "{version}"
version_variables = [
  "src/dummy/__about__.py:__version__",
]
build_command = """
python -m pip install build
python -m build
"""
changelog.template_dir = ".github/templates"
changelog.environment.keep_trailing_newline = true
